---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: certs
  name: dns-editor
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "delete", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
